# Generated by Django 5.0.2 on 2024-02-19 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
